export const TASK_ORDER = [
  "download-starter-workspace",
  "select-source-application",
  "create-migration-agents",
  "create-migration-context",
  "start-source-app",
  "validate-source-app",
  "run-discovery-agent",
  "rank-aws-archetypes",
  "map-chat-completions-to-responses",
  "challenge-migration-decisions",
  "resolve-migration-findings",
  "prepare-live-bedrock",
  "approve-migration-contract",
  "generate-target-app",
  "validate-target-app",
  "test-migrated-app-live",
  "generate-deployment-package",
  "validate-deployment-package",
  "preflight-aws-account",
  "deploy-aws-environment",
  "test-deployed-application",
  "package-migration-plugin",
  "destroy-workshop-environment",
] as const;
